In [2]:
import numpy as np
B = np.arange(3)
print (B)
print (np.exp(B))
print (np.sqrt(B))

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


In [5]:
#Return the floor of the input
a = np.floor(10*np.random.random((3,4)))
print (a)
print ('--------')
#a.shape
## flatten the array
print (a.ravel())
print ('--------')
a.shape = (6, 2)
print (a) 
print ('--------')
print (a.T)


#If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
#a.reshape(3,-1)

[[ 6.  7.  2.  9.]
 [ 6.  0.  5.  2.]
 [ 9.  0.  9.  6.]]
--------
[ 6.  7.  2.  9.  6.  0.  5.  2.  9.  0.  9.  6.]
--------
[[ 6.  7.]
 [ 2.  9.]
 [ 6.  0.]
 [ 5.  2.]
 [ 9.  0.]
 [ 9.  6.]]
--------
[[ 6.  2.  6.  5.  9.  9.]
 [ 7.  9.  0.  2.  0.  6.]]


In [1]:
import numpy as np
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print (a)
print ('---')
print (b)
print ('---')
print (np.vstack((a,b)))
#np.hstack((a,b))

[[ 3.  7.]
 [ 2.  6.]]
---
[[ 9.  6.]
 [ 0.  7.]]
---
[[ 3.  7.]
 [ 2.  6.]
 [ 9.  6.]
 [ 0.  7.]]


In [9]:
a = np.floor(10*np.random.random((2,12)))
print (a)
print ('---')
print (np.hsplit(a,3))
print ('---')
print (np.hsplit(a,(3,4)))   # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12,2)))
print ('---')
print (a)
np.vsplit(a,3)

[[ 8.  3.  3.  5.  9.  0.  1.  1.  6.  2.  7.  2.]
 [ 7.  1.  9.  7.  5.  2.  5.  7.  0.  3.  1.  1.]]
---
[array([[ 8.,  3.,  3.,  5.],
       [ 7.,  1.,  9.,  7.]]), array([[ 9.,  0.,  1.,  1.],
       [ 5.,  2.,  5.,  7.]]), array([[ 6.,  2.,  7.,  2.],
       [ 0.,  3.,  1.,  1.]])]
---
[array([[ 8.,  3.,  3.],
       [ 7.,  1.,  9.]]), array([[ 5.],
       [ 7.]]), array([[ 9.,  0.,  1.,  1.,  6.,  2.,  7.,  2.],
       [ 5.,  2.,  5.,  7.,  0.,  3.,  1.,  1.]])]
---
[[ 8.  1.]
 [ 3.  2.]
 [ 8.  0.]
 [ 9.  0.]
 [ 9.  0.]
 [ 5.  3.]
 [ 3.  3.]
 [ 7.  2.]
 [ 5.  7.]
 [ 9.  6.]
 [ 4.  0.]
 [ 8.  4.]]


[array([[ 8.,  1.],
        [ 3.,  2.],
        [ 8.,  0.],
        [ 9.,  0.]]), array([[ 9.,  0.],
        [ 5.,  3.],
        [ 3.,  3.],
        [ 7.,  2.]]), array([[ 5.,  7.],
        [ 9.,  6.],
        [ 4.,  0.],
        [ 8.,  4.]])]

In [12]:
#Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
print (b is a)
b.shape = 3,4
print (a.shape)
print (id(a))
print (id(b))

True
(3, 4)
1974659569504
1974659569504


In [15]:
#The view method creates a new array object that looks at the same data.
c = a.view()
print (c is a)
c.shape = 2,6
print (a.shape)
c[0,4] = 1234
print (a)
print (id(a))
print (id(c))

False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
1974659569504
1974659621312


In [16]:
#The copy method makes a complete copy of the array and its data.
d = a.copy() 
d is a
d[0,0] = 9999
print (d) 
print (a)

[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
